# These are supported funding model platforms

# GitHub Sponsors
# github: [ConsciousEnergy]  # Uncomment when GitHub Sponsors is set up

# Custom donation links
custom: ['https://conscious.energy/donations/', 'https://www.gofundme.com/f/iccf25-conscious-energy']

